name: asroo_store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  cupertino_icons: ^1.0.8
  #Core
  # connectivity_plus: ^6.1.2
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3

  #Firebase
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/play_store_512.png"

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - assets/images/core/
  # example:
  # fonts:
  #   - family: S
  #     fonts:
  #       - asset: fonts/S-Regular.ttf
  #       - asset: fonts/S-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
